import React, { createContext, useContext, useState, useEffect, useMemo } from 'react';

export type Language = 'en' | 'vi' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations = {
  en: {
    common: {
      search: 'Search employees, roles, or files...',
      logout: 'Logout',
      loading: 'Loading...',
      welcome: 'Welcome',
      submit: 'Submit',
      cancel: 'Cancel',
      confirm: 'Confirm',
      save: 'Save',
      actions: 'Actions',
      export: 'Export Excel',
      edit: 'Edit',
      delete: 'Delete',
      approve: 'Approve',
      reject: 'Reject',
      yes: 'Yes',
      no: 'No',
      noRecords: 'No records found',
    },
    sidebar: {
      dashboard: 'Dashboard',
      employees: 'Employee Directory',
      onboarding: 'Onboarding',
      attendance: 'Attendance',
      leave: 'Leave Requests',
      payroll: 'Payroll & Salary',
      reports: 'Reports',
      chatbot: 'ChatBox AI',
      departments: 'Departments',
      companyConfigs: 'Company Configs',
      projects: 'Projects',
      explanations: 'Explanations',
      overtime: 'Overtime',
      holidays: 'Holidays',
      notifications: 'Notifications',
      userRoles: 'User Roles',
      enterprise: 'Enterprise Edition',
      portal: 'HR Portal',
    },
    login: {
      title: 'HR Portal',
      desc: 'Enterprise Edition',
      welcome: 'Welcome back!',
      subtitle: 'Sign in to manage employees, payroll, and view HR insights.',
      email: 'Email Address',
      password: 'Password',
      signingIn: 'Signing in...',
      signIn: 'Sign In',
      securedBy: 'Secured by',
      emailRequired: 'Email is required',
      passwordRequired: 'Password is required',
      unifiedLabel: 'Unified HR Platform',
      unifiedTitle: 'People, Payroll &',
      unifiedTitle2: 'AI — Together.',
      unifiedDesc: 'Manage employees, attendance, leave, salary, recruitment pipeline, performance reviews, and AI-powered HR support from one unified console.',
      feature1Label: 'Employee Management',
      feature1Desc: 'Profiles, departments & org structure',
      feature2Label: 'Attendance & Leave',
      feature2Desc: 'Real-time tracking and approvals',
      feature3Label: 'Payroll Engine',
      feature3Desc: 'Auto-calculate, confirm and export',
      feature4Label: 'Recruitment Pipeline',
      feature4Desc: 'Track candidates from apply to hire',
      feature5Label: 'AI HR Assistant',
      feature5Desc: 'Natural language HR query engine',
      signInTitle: 'Welcome back',
      signInDesc: 'Sign in to your HR AI System account.',
    },
    dashboard: {
      title: 'Dashboard',
      subtitle: 'Operational summary across leave, attendance, payroll, and performance.',
      totalEmployees: 'Total Employees',
      activeRequests: 'Active Requests',
      attendanceRate: 'Attendance Rate',
      monthlyPayroll: 'Monthly Payroll',
      quickActions: 'Quick Actions',
      requestLeave: 'Request Leave',
      calcPayroll: 'Calculate Payroll',
      chatbot: 'Ask HR Assistant',
      onTime: 'On Time',
      late: 'Late',
      absent: 'Absent',
      actualDays: 'Actual Days',
      netSalary: 'Net Salary',
      latestKpi: 'Latest KPI',
      kpiTrend: 'KPI Performance Trend',
      weeklyBreakdown: 'Weekly Score Breakdown',
      leaveTrend: 'Days available this year',
      attendanceTrend: 'Working days this month',
      salaryTrend: 'Latest confirmed payslip',
      performanceTrend: 'Performance score (0–100)',
    },
    chatbot: {
      title: 'HR Assistant Chatbot',
      subtitle: 'Ask about leave balance, payroll, attendance, policy, and HR workflows.',
      placeholder: 'Type your HR question here...',
      send: 'Send',
      newChat: 'New conversation',
      history: 'Chat history',
      faqs: 'Common FAQs',
      askAnything: 'Ask HR Bot anything',
      welcomeDesc: 'Leave balance, salary slips, attendance, OT rules, or company policies.',
      ready: 'Online · Ready to help',
      reply1: 'My remaining leave?',
      reply2: 'My recent salary slip?',
      reply3: 'My attendance this month?',
      reply4: 'Company OT rules?',
      faq1: 'How do I request PTO?',
      faq2: 'Medical insurance claims',
      faq3: 'Referral program details',
      faq4: 'Internal job board',
    },
    leave: {
      title: 'Leave',
      subtitle: 'Submit leave requests and review approvals.',
      total: 'Total',
      used: 'Used',
      remaining: 'Remaining',
      newRequest: 'New leave request',
      myRequests: 'My leave requests',
      hrApprovals: 'HR approvals',
      startDate: 'Start date',
      endDate: 'End date',
      reason: 'Reason',
      submitRequest: 'Submit leave request',
      startDateRequired: 'Start date is required',
      endDateRequired: 'End date is required',
      endDateAfterStart: 'End date must be after start date',
      id: 'ID',
      dates: 'Dates',
      days: 'Days',
      status: 'Status',
      noAction: 'No action',
    },
    salary: {
      title: 'Salary',
      subtitle: 'Configure salary, calculate payroll, confirm, mark paid, and export Excel.',
      config: 'Salary config',
      actions: 'Payroll actions',
      history: 'Payroll history',
      baseSalary: 'Base salary',
      bhxhSalary: 'BHXH salary',
      taxDependents: 'Tax dependents',
      effectiveDate: 'Effective date',
      allowancesJson: 'Allowances JSON',
      saveConfig: 'Save salary config',
      month: 'Month',
      year: 'Year',
      bonus: 'Bonus',
      advance: 'Advance',
      calculateMine: 'Calculate mine',
      calculateAll: 'Calculate all active',
      exportExcel: 'Export Excel',
      employee: 'Employee',
      period: 'Period',
      actualDays: 'Actual days',
      netSalary: 'Net salary',
      status: 'Status',
      employeeRequired: 'Employee ID is required',
      baseSalaryRequired: 'Base salary is required',
    },
    recruitment: {
      title: 'Recruitment',
      subtitle: 'Create jobs, upload CVs, and manage AI-assisted candidate pipeline.',
      createJob: 'Create job',
      openJobs: 'Open jobs',
      uploadCv: 'Upload CV',
      pipeline: 'Pipeline',
      titleColumn: 'Title',
      department: 'Department',
      deadline: 'Deadline',
      status: 'Status',
      candidate: 'Candidate',
      score: 'Score',
      stage: 'Stage',
      select: 'Select',
      close: 'Close',
      interview: 'Interview',
      hire: 'Hire',
      candidateName: 'Candidate name',
      candidateEmail: 'Candidate email',
      candidatePhone: 'Candidate phone',
      cvFile: 'CV file',
      jobTitle: 'Title',
      selectDepartment: 'Select department',
      description: 'Description',
      requirements: 'Requirements',
      skills: 'Skills, comma separated',
      salaryRange: 'Salary range',
      headcount: 'Headcount',
    },
    performance: {
      title: 'Performance',
      subtitle: 'Track weekly KPI records and AI-assisted trend analysis.',
      newKpi: 'New KPI',
      kpiRecords: 'KPI records',
      analyzeMine: 'Analyze mine',
      analysisDashboard: 'Analysis dashboard',
      analyzeAll: 'Analyze all',
      weekStart: 'Week start',
      kpiScore: 'KPI score',
      tasksDone: 'Tasks done',
      tasksTotal: 'Tasks total',
      workHours: 'Work hours',
      lateDays: 'Late days',
      saveKpi: 'Save KPI',
      week: 'Week',
      score: 'Score',
      tasks: 'Tasks',
      hours: 'Hours',
      late: 'Late',
      employee: 'Employee',
      trend: 'Trend',
      changePct: 'Change %',
      alert: 'Alert',
      message: 'Message',
    },
    modules: {
      projectsTitle: 'Projects',
      projectsDesc: 'Manage projects by PM, HR and Admin permissions.',
      createProject: 'Create project',
      updateProject: 'Update project',
      projectList: 'Project list',
      holidaysTitle: 'Holidays',
      holidaysDesc: 'Company-wide holiday calendar.',
      createHoliday: 'Create holiday',
      updateHoliday: 'Update holiday',
      holidayList: 'Holiday list',
      notificationsTitle: 'Notifications',
      notificationsDesc: 'Personal and system-wide notifications.',
      createNotification: 'Create notification',
      myNotifications: 'My notifications',
      allNotifications: 'All notifications',
      overtimeTitle: 'Overtime',
      overtimeDesc: 'Request and approve overtime by permission.',
      requestOvertime: 'Request overtime',
      myOvertime: 'My overtime requests',
      overtimeApprovals: 'Overtime approvals',
      explanationsTitle: 'Attendance explanations',
      explanationsDesc: 'Submit and review attendance explanations.',
      submitExplanation: 'Submit explanation',
      myExplanations: 'My explanations',
      explanationApprovals: 'Explanation approvals',
      companyTitle: 'Company work policy',
      companyDesc: 'Working days, check-in/check-out time, lunch break, half-day coefficients, OT coefficients and attendance closing day.',
      workSchedule: 'Work schedule',
      coefficients: 'Attendance and OT coefficients',
      saveWorkPolicy: 'Save work policy',
      userRolesTitle: 'User roles',
      userRolesDesc: 'Only Admin can update user roles.',
      updateUserRole: 'Update user role',
      name: 'Name',
      titleField: 'Title',
      content: 'Content',
      message: 'Message',
      description: 'Description',
      department: 'Department',
      manager: 'Manager',
      start: 'Start',
      end: 'End',
      date: 'Date',
      time: 'Time',
      reason: 'Reason',
      status: 'Status',
      employee: 'Employee',
      reviewerNote: 'Reviewer note',
      target: 'Target',
      created: 'Created',
      paid: 'Paid',
      noDepartment: 'No department',
      noManager: 'No manager',
      allRoles: 'All roles',
      saveProject: 'Save project',
      saveHoliday: 'Save holiday',
      submitRequest: 'Submit request',
      updatedBy: 'Updated by',
      workingDays: 'Working days in week',
      checkInTime: 'Check-in time',
      checkOutTime: 'Check-out time',
      earlyCheckInMinutes: 'Allowed early check-in (minutes)',
      lunchStart: 'Lunch break start',
      lunchEnd: 'Lunch break end',
      lunchMinutes: 'Lunch break minutes',
      morningHalfCoefficient: 'Morning half-day coefficient',
      afternoonHalfCoefficient: 'Afternoon half-day coefficient',
      otWorkingDay: 'Working-day OT',
      otDayOff: 'Day-off OT',
      otOfficialHoliday: 'Official-holiday OT',
      otCompensatoryHoliday: 'Compensatory-holiday OT',
      closingDay: 'Monthly attendance closing day',
      standardWorkingDays: 'Standard working days per month',
      userId: 'User ID',
      role: 'Role',
      updateRole: 'Update role',
      userRoleHelp: 'Enter backend userId and the new role.',
    },
  },
  vi: {
    common: {
      search: 'Tìm kiếm nhân viên, chức vụ, tài liệu...',
      logout: 'Đăng xuất',
      loading: 'Đang tải...',
      welcome: 'Chào mừng',
      submit: 'Gửi đi',
      cancel: 'Hủy',
      confirm: 'Xác nhận',
      save: 'Lưu lại',
      actions: 'Thao tác',
      export: 'Xuất Excel',
      edit: 'Sửa',
      delete: 'Xóa',
      approve: 'Duyệt',
      reject: 'Từ chối',
      yes: 'Có',
      no: 'Không',
      noRecords: 'Không có dữ liệu',
    },
    sidebar: {
      dashboard: 'Tổng quan',
      employees: 'Danh sách nhân viên',
      onboarding: 'Onboarding',
      attendance: 'Chấm công',
      leave: 'Đơn xin nghỉ phép',
      payroll: 'Lương & Bảng công',
      reports: 'Báo cáo hiệu suất',
      chatbot: 'Trợ lý ChatBox AI',
      departments: 'Phòng ban',
      companyConfigs: 'Cấu hình công ty',
      projects: 'Dự án',
      explanations: 'Giải trình',
      overtime: 'Tăng ca',
      holidays: 'Ngày lễ',
      notifications: 'Thông báo',
      userRoles: 'Phân quyền user',
      enterprise: 'Phiên bản Doanh nghiệp',
      portal: 'HR Portal',
    },
    login: {
      title: 'HR Portal',
      desc: 'Phiên bản Doanh nghiệp',
      welcome: 'Chào mừng trở lại!',
      subtitle: 'Đăng nhập để quản lý nhân sự, bảng lương và xem báo cáo phân tích.',
      email: 'Địa chỉ Email',
      password: 'Mật khẩu',
      signingIn: 'Đang đăng nhập...',
      signIn: 'Đăng nhập',
      securedBy: 'Được bảo mật bởi',
      emailRequired: 'Vui lòng nhập Email',
      passwordRequired: 'Vui lòng nhập Mật khẩu',
      unifiedLabel: 'Nền tảng HR Hợp nhất',
      unifiedTitle: 'Nhân sự, Lương &',
      unifiedTitle2: 'AI — Hợp nhất.',
      unifiedDesc: 'Quản lý nhân sự, chấm công, nghỉ phép, tính lương, quy trình tuyển dụng, đánh giá hiệu suất và trợ lý AI từ một giao diện hợp nhất.',
      feature1Label: 'Quản lý Nhân sự',
      feature1Desc: 'Thông tin hồ sơ, phòng ban & cơ cấu tổ chức',
      feature2Label: 'Chấm công & Phép',
      feature2Desc: 'Theo dõi thời gian thực tế và phê duyệt đơn',
      feature3Label: 'Công cụ tính Lương',
      feature3Desc: 'Tự động tính lương, phê duyệt và xuất dữ liệu',
      feature4Label: 'Quy trình Tuyển dụng',
      feature4Desc: 'Theo dõi ứng viên từ lúc nộp đơn đến nhận việc',
      feature5Label: 'Trợ lý ảo HR AI',
      feature5Desc: 'Hỏi đáp nhân sự thông minh bằng ngôn ngữ tự nhiên',
      signInTitle: 'Chào mừng trở lại',
      signInDesc: 'Đăng nhập vào tài khoản HR AI System của bạn.',
    },
    dashboard: {
      title: 'Bảng điều khiển',
      subtitle: 'Tóm tắt hoạt động nghỉ phép, chấm công, bảng lương và hiệu suất công việc.',
      totalEmployees: 'Tổng nhân viên',
      activeRequests: 'Yêu cầu chờ duyệt',
      attendanceRate: 'Tỷ lệ đi làm',
      monthlyPayroll: 'Tổng chi lương tháng',
      quickActions: 'Thao tác nhanh',
      requestLeave: 'Đăng ký nghỉ phép',
      calcPayroll: 'Tính toán bảng lương',
      chatbot: 'Hỏi Trợ lý ảo HR',
      onTime: 'Đúng giờ',
      late: 'Đi muộn',
      absent: 'Vắng mặt',
      actualDays: 'Ngày thực tế',
      netSalary: 'Lương thực lĩnh',
      latestKpi: 'KPI mới nhất',
      kpiTrend: 'Xu hướng hiệu suất KPI',
      weeklyBreakdown: 'Chi tiết điểm số tuần',
      leaveTrend: 'Số ngày phép khả dụng năm nay',
      attendanceTrend: 'Số ngày làm việc tháng này',
      salaryTrend: 'Bảng lương xác nhận gần nhất',
      performanceTrend: 'Điểm hiệu suất (0–100)',
    },
    chatbot: {
      title: 'Trợ lý ảo HR AI',
      subtitle: 'Hỏi về số ngày phép, phiếu lương, chấm công, quy chế công ty và quy trình HR.',
      placeholder: 'Nhập câu hỏi nhân sự tại đây...',
      send: 'Gửi',
      newChat: 'Cuộc trò chuyện mới',
      history: 'Lịch sử trò chuyện',
      faqs: 'Câu hỏi thường gặp',
      askAnything: 'Hỏi HR Bot bất cứ điều gì',
      welcomeDesc: 'Số ngày nghỉ phép, phiếu lương, chấm công, quy định làm thêm giờ hoặc chính sách công ty.',
      ready: 'Trực tuyến · Sẵn sàng trợ giúp',
      reply1: 'Phép còn lại của tôi?',
      reply2: 'Lương tháng gần nhất?',
      reply3: 'Chấm công tháng này?',
      reply4: 'Quy định OT của công ty?',
      faq1: 'Làm thế nào để xin nghỉ phép?',
      faq2: 'Quy trình yêu cầu bảo hiểm y tế?',
      faq3: 'Chi tiết chương trình giới thiệu?',
      faq4: 'Bảng tin tuyển dụng nội bộ?',
    },
    leave: {
      title: 'Nghỉ phép',
      subtitle: 'Nộp đơn xin nghỉ phép và duyệt các yêu cầu của nhân viên.',
      total: 'Tổng số phép',
      used: 'Đã dùng',
      remaining: 'Còn lại',
      newRequest: 'Tạo yêu cầu nghỉ phép mới',
      myRequests: 'Yêu cầu phép của tôi',
      hrApprovals: 'Phê duyệt của nhân sự',
      startDate: 'Ngày bắt đầu',
      endDate: 'Ngày kết thúc',
      reason: 'Lý do',
      submitRequest: 'Gửi đơn xin nghỉ',
      startDateRequired: 'Vui lòng chọn ngày bắt đầu',
      endDateRequired: 'Vui lòng chọn ngày kết thúc',
      endDateAfterStart: 'Ngày kết thúc phải sau ngày bắt đầu',
      id: 'Mã đơn',
      dates: 'Ngày nghỉ',
      days: 'Số ngày',
      status: 'Trạng thái',
      noAction: 'Không có thao tác',
    },
    salary: {
      title: 'Lương & Payroll',
      subtitle: 'Cấu hình lương, tính toán bảng lương, xác nhận, đánh dấu đã thanh toán và xuất Excel.',
      config: 'Cấu hình lương',
      actions: 'Tính năng bảng lương',
      history: 'Lịch sử tính lương',
      baseSalary: 'Lương cơ bản',
      bhxhSalary: 'Lương BHXH',
      taxDependents: 'Người phụ thuộc tính thuế',
      effectiveDate: 'Ngày hiệu lực',
      allowancesJson: 'Phụ cấp (JSON)',
      saveConfig: 'Lưu cấu hình lương',
      month: 'Tháng',
      year: 'Năm',
      bonus: 'Thưởng',
      advance: 'Tạm ứng',
      calculateMine: 'Tính lương của tôi',
      calculateAll: 'Tính lương tất cả',
      exportExcel: 'Xuất Excel',
      employee: 'Nhân viên',
      period: 'Kỳ lương',
      actualDays: 'Ngày thực làm',
      netSalary: 'Lương thực lĩnh',
      status: 'Trạng thái',
      employeeRequired: 'Cần có mã nhân viên',
      baseSalaryRequired: 'Vui lòng nhập lương cơ bản',
    },
    recruitment: {
      title: 'Tuyển dụng',
      subtitle: 'Tạo tin tuyển dụng, upload CV và quản lý pipeline ứng viên với AI.',
      createJob: 'Tạo tin tuyển dụng',
      openJobs: 'Vị trí đang mở',
      uploadCv: 'Upload CV',
      pipeline: 'Pipeline ứng viên',
      titleColumn: 'Tiêu đề',
      department: 'Phòng ban',
      deadline: 'Hạn nộp',
      status: 'Trạng thái',
      candidate: 'Ứng viên',
      score: 'Điểm',
      stage: 'Giai đoạn',
      select: 'Chọn',
      close: 'Đóng',
      interview: 'Phỏng vấn',
      hire: 'Tuyển',
      candidateName: 'Tên ứng viên',
      candidateEmail: 'Email ứng viên',
      candidatePhone: 'SĐT ứng viên',
      cvFile: 'File CV',
      jobTitle: 'Tiêu đề',
      selectDepartment: 'Chọn phòng ban',
      description: 'Mô tả',
      requirements: 'Yêu cầu',
      skills: 'Kỹ năng, phân tách bằng dấu phẩy',
      salaryRange: 'Khoảng lương',
      headcount: 'Số lượng',
    },
    performance: {
      title: 'Báo cáo hiệu suất',
      subtitle: 'Theo dõi KPI hàng tuần và phân tích xu hướng bằng AI.',
      newKpi: 'Thêm KPI mới',
      kpiRecords: 'Danh sách KPI',
      analyzeMine: 'Phân tích của tôi',
      analysisDashboard: 'Dashboard phân tích',
      analyzeAll: 'Phân tích tất cả',
      weekStart: 'Tuần bắt đầu',
      kpiScore: 'Điểm KPI',
      tasksDone: 'Task hoàn thành',
      tasksTotal: 'Tổng số task',
      workHours: 'Số giờ làm',
      lateDays: 'Số ngày muộn',
      saveKpi: 'Lưu KPI',
      week: 'Tuần',
      score: 'Điểm',
      tasks: 'Task',
      hours: 'Giờ làm',
      late: 'Muộn',
      employee: 'Nhân viên',
      trend: 'Xu hướng',
      changePct: 'Thay đổi %',
      alert: 'Cảnh báo',
      message: 'Ghi chú',
    },
    modules: {
      projectsTitle: 'Dự án',
      projectsDesc: 'Quản lý dự án theo quyền PM, HR và Admin.',
      createProject: 'Tạo dự án',
      updateProject: 'Cập nhật dự án',
      projectList: 'Danh sách dự án',
      holidaysTitle: 'Ngày lễ',
      holidaysDesc: 'Lịch ngày lễ dùng chung toàn công ty.',
      createHoliday: 'Tạo ngày lễ',
      updateHoliday: 'Cập nhật ngày lễ',
      holidayList: 'Danh sách ngày lễ',
      notificationsTitle: 'Thông báo',
      notificationsDesc: 'Thông báo cá nhân và thông báo toàn hệ thống.',
      createNotification: 'Tạo thông báo',
      myNotifications: 'Thông báo của tôi',
      allNotifications: 'Tất cả thông báo',
      overtimeTitle: 'Tăng ca',
      overtimeDesc: 'Đăng ký và duyệt tăng ca theo quyền.',
      requestOvertime: 'Đăng ký tăng ca',
      myOvertime: 'Đơn tăng ca của tôi',
      overtimeApprovals: 'Duyệt tăng ca',
      explanationsTitle: 'Giải trình chấm công',
      explanationsDesc: 'Gửi và duyệt giải trình chấm công.',
      submitExplanation: 'Gửi giải trình',
      myExplanations: 'Giải trình của tôi',
      explanationApprovals: 'Duyệt giải trình',
      companyTitle: 'Thông tin làm việc công ty',
      companyDesc: 'Ngày làm việc, giờ check-in/check-out, nghỉ trưa, hệ số nửa ngày, hệ số OT và ngày chốt công.',
      workSchedule: 'Lịch làm việc',
      coefficients: 'Quy đổi công và OT',
      saveWorkPolicy: 'Lưu thông tin làm việc',
      userRolesTitle: 'Phân quyền user',
      userRolesDesc: 'Chỉ Admin được sửa role user.',
      updateUserRole: 'Cập nhật role user',
      name: 'Tên',
      titleField: 'Tiêu đề',
      content: 'Nội dung',
      message: 'Tin nhắn',
      description: 'Mô tả',
      department: 'Phòng ban',
      manager: 'Quản lý',
      start: 'Bắt đầu',
      end: 'Kết thúc',
      date: 'Ngày',
      time: 'Thời gian',
      reason: 'Lý do',
      status: 'Trạng thái',
      employee: 'Nhân viên',
      reviewerNote: 'Ghi chú duyệt',
      target: 'Đối tượng nhận',
      created: 'Ngày tạo',
      paid: 'Có lương',
      noDepartment: 'Không gắn phòng ban',
      noManager: 'Không gắn quản lý',
      allRoles: 'Tất cả role',
      saveProject: 'Lưu dự án',
      saveHoliday: 'Lưu ngày lễ',
      submitRequest: 'Gửi yêu cầu',
      updatedBy: 'Cập nhật bởi',
      workingDays: 'Các ngày làm việc trong tuần',
      checkInTime: 'Thời gian check-in',
      checkOutTime: 'Thời gian check-out',
      earlyCheckInMinutes: 'Cho phép check-in sớm (phút)',
      lunchStart: 'Bắt đầu nghỉ trưa',
      lunchEnd: 'Kết thúc nghỉ trưa',
      lunchMinutes: 'Số phút nghỉ trưa',
      morningHalfCoefficient: 'Hệ số nghỉ sáng',
      afternoonHalfCoefficient: 'Hệ số nghỉ chiều',
      otWorkingDay: 'OT ngày làm việc',
      otDayOff: 'OT ngày nghỉ',
      otOfficialHoliday: 'OT ngày lễ chính thức',
      otCompensatoryHoliday: 'OT ngày lễ bù',
      closingDay: 'Ngày chốt công hằng tháng',
      standardWorkingDays: 'Công chuẩn tháng',
      userId: 'User ID',
      role: 'Role',
      updateRole: 'Cập nhật role',
      userRoleHelp: 'Nhập userId backend và role mới.',
    },
  },
  zh: {
    common: {
      search: '搜索员工、职位或文件...',
      logout: '退出登录',
      loading: '加载中...',
      welcome: '欢迎',
      submit: '提交',
      cancel: '取消',
      confirm: '确认',
      save: '保存',
      actions: '操作',
      export: '导出 Excel',
      edit: '编辑',
      delete: '删除',
      approve: '批准',
      reject: '拒绝',
      yes: '是',
      no: '否',
      noRecords: '暂无数据',
    },
    sidebar: {
      dashboard: '控制面板',
      employees: '员工名册',
      onboarding: '入职管理',
      attendance: '考勤管理',
      leave: '请假申请',
      payroll: '薪资与工资表',
      reports: '业绩报告',
      chatbot: '智能助手 ChatBox AI',
      departments: '部门',
      companyConfigs: '公司配置',
      projects: '项目',
      explanations: '考勤说明',
      overtime: '加班',
      holidays: '节假日',
      notifications: '通知',
      userRoles: '用户角色',
      enterprise: '企业特别版',
      portal: 'HR 门户系统',
    },
    login: {
      title: 'HR 门户系统',
      desc: '企业特别版',
      welcome: '欢迎回来！',
      subtitle: '登录系统以管理员工、计算薪资并查看人力资源分析报告。',
      email: '电子邮箱地址',
      password: '安全密码',
      signingIn: '正在登录...',
      signIn: '确认登录',
      securedBy: '安全保障由',
      emailRequired: '邮箱地址是必填项',
      passwordRequired: '安全密码是必填项',
      unifiedLabel: '一体化人力资源平台',
      unifiedTitle: '员工、薪资与',
      unifiedTitle2: '人工智能 — 一体化。',
      unifiedDesc: '在统一的管理控制台中管理员工、考勤、请假、薪资计算、招聘漏斗、绩效评估以及 AI 智能助手。',
      feature1Label: '员工管理系统',
      feature1Desc: '员工档案、部门架构与组织关系',
      feature2Label: '考勤与休假管理',
      feature2Desc: '实时出勤跟踪、打卡与请假审批',
      feature3Label: '智能薪资计算引擎',
      feature3Desc: '自动算薪、确认发放并导出 Excel',
      feature4Label: '招聘与入职管理',
      feature4Desc: '跟踪从简历投递到录用入职的全流程',
      feature5Label: 'HR 智能问答助理',
      feature5Desc: '基于自然语言处理的人力资源查询引擎',
      signInTitle: '欢迎回来',
      signInDesc: '登录您的 HR AI 账户。',
    },
    dashboard: {
      title: '控制面板',
      subtitle: '涵盖请假、考勤、工资及绩效的业务汇总。',
      totalEmployees: '员工总数',
      activeRequests: '待审批申请',
      attendanceRate: '出勤率',
      monthlyPayroll: '月度薪资总额',
      quickActions: '快捷操作',
      requestLeave: '申请请假',
      calcPayroll: '计算薪资表',
      chatbot: '咨询智能助手',
      onTime: '准时',
      late: '迟到',
      absent: '缺勤',
      actualDays: '实际出勤天数',
      netSalary: '实发薪资',
      latestKpi: '最新 KPI 指标',
      kpiTrend: 'KPI 绩效变化趋势',
      weeklyBreakdown: '每周绩效得分细化',
      leaveTrend: '今年剩余可用假期天数',
      attendanceTrend: '本月内累计出勤天数',
      salaryTrend: '最新已确认的工资单',
      performanceTrend: '绩效分数范围 (0-100)',
    },
    chatbot: {
      title: 'HR 智能助理',
      subtitle: '咨询关于年假余额、工资单、考勤、加班规则和公司制度。',
      placeholder: '在此输入您的人力资源问题...',
      send: '发送',
      newChat: '新对话',
      history: '历史对话',
      faqs: '常见问题列表',
      askAnything: '向 HR 机器人提问',
      welcomeDesc: '年假余额、工资单、考勤、加班规则或公司政策。',
      ready: '在线 · 随时准备为您服务',
      reply1: '我的剩余假期数？',
      reply2: '我最近的工资单？',
      reply3: '我本月的出勤记录？',
      reply4: '公司加班规定？',
      faq1: '我该如何申请休假？',
      faq2: '医疗保险理赔流程',
      faq3: '内部员工推荐奖金',
      faq4: '内部招聘公告栏',
    },
    leave: {
      title: '请假管理',
      subtitle: '提交请假申请并审核员工请假申请。',
      total: '总假期额',
      used: '已用天数',
      remaining: '剩余天数',
      newRequest: '新建请假申请',
      myRequests: '我的请假历史',
      hrApprovals: 'HR 审批人列表',
      startDate: '开始日期',
      endDate: '结束日期',
      reason: '原因',
      submitRequest: '提交请假申请',
      startDateRequired: '请选择开始日期',
      endDateRequired: '请选择结束日期',
      endDateAfterStart: '结束日期必须晚于开始日期',
      id: '编号',
      dates: '假期日期',
      days: '天数',
      status: '状态',
      noAction: '无操作',
    },
    salary: {
      title: '薪金与工资表',
      subtitle: '配置基础薪资、计算工资表、确认发放、标记已付并导出 Excel 表格。',
      config: '基础薪资配置',
      actions: '工资表操作栏',
      history: '薪资发放记录',
      baseSalary: '基础工资',
      bhxhSalary: '社会保险工资',
      taxDependents: '纳税赡养人数',
      effectiveDate: '生效日期',
      allowancesJson: '津贴配置（JSON）',
      saveConfig: '保存工资配置',
      month: '月份',
      year: '年份',
      bonus: '奖金',
      advance: '预支',
      calculateMine: '计算我的薪资',
      calculateAll: '计算所有在职员工',
      exportExcel: '导出 Excel',
      employee: '员工',
      period: '薪资周期',
      actualDays: '实际出勤天数',
      netSalary: '实发薪资',
      status: '状态',
      employeeRequired: '员工 ID 为必填项',
      baseSalaryRequired: '请输入基础薪资',
    },
    recruitment: {
      title: '招聘管理',
      subtitle: '创建职位、上传简历并管理 AI 辅助候选人流程。',
      createJob: '创建职位',
      openJobs: '开放职位',
      uploadCv: '上传简历',
      pipeline: '候选人流程',
      titleColumn: '标题',
      department: '部门',
      deadline: '截止日期',
      status: '状态',
      candidate: '候选人',
      score: '分数',
      stage: '阶段',
      select: '选择',
      close: '关闭',
      interview: '面试',
      hire: '录用',
      candidateName: '候选人姓名',
      candidateEmail: '候选人邮箱',
      candidatePhone: '候选人电话',
      cvFile: '简历文件',
      jobTitle: '标题',
      selectDepartment: '选择部门',
      description: '描述',
      requirements: '要求',
      skills: '技能，用逗号分隔',
      salaryRange: '薪资范围',
      headcount: '招聘人数',
    },
    performance: {
      title: '业绩报告',
      subtitle: '跟踪每周 KPI 记录及 AI 辅助趋势分析。',
      newKpi: '新增 KPI',
      kpiRecords: 'KPI 记录',
      analyzeMine: '分析我的绩效',
      analysisDashboard: '分析仪表板',
      analyzeAll: '分析全部员工',
      weekStart: '周开始日期',
      kpiScore: 'KPI 分数',
      tasksDone: '已完成任务',
      tasksTotal: '总任务数',
      workHours: '工作小时数',
      lateDays: '迟到天数',
      saveKpi: '保存 KPI',
      week: '周',
      score: '分数',
      tasks: '任务',
      hours: '小时',
      late: '迟到',
      employee: '员工',
      trend: '趋势',
      changePct: '变化百分比',
      alert: '警报',
      message: '消息',
    },
    modules: {
      projectsTitle: '项目',
      projectsDesc: '按 PM、HR 和 Admin 权限管理项目。',
      createProject: '创建项目',
      updateProject: '更新项目',
      projectList: '项目列表',
      holidaysTitle: '节假日',
      holidaysDesc: '公司统一节假日日历。',
      createHoliday: '创建节假日',
      updateHoliday: '更新节假日',
      holidayList: '节假日列表',
      notificationsTitle: '通知',
      notificationsDesc: '个人通知和系统通知。',
      createNotification: '创建通知',
      myNotifications: '我的通知',
      allNotifications: '全部通知',
      overtimeTitle: '加班',
      overtimeDesc: '按权限申请和审批加班。',
      requestOvertime: '申请加班',
      myOvertime: '我的加班申请',
      overtimeApprovals: '加班审批',
      explanationsTitle: '考勤说明',
      explanationsDesc: '提交和审核考勤说明。',
      submitExplanation: '提交说明',
      myExplanations: '我的说明',
      explanationApprovals: '说明审批',
      companyTitle: '公司工作政策',
      companyDesc: '工作日、签到/签退时间、午休、半天系数、加班系数和考勤结算日。',
      workSchedule: '工作日程',
      coefficients: '考勤与加班系数',
      saveWorkPolicy: '保存工作政策',
      userRolesTitle: '用户角色',
      userRolesDesc: '只有 Admin 可以更新用户角色。',
      updateUserRole: '更新用户角色',
      name: '名称',
      titleField: '标题',
      content: '内容',
      message: '消息',
      description: '描述',
      department: '部门',
      manager: '负责人',
      start: '开始',
      end: '结束',
      date: '日期',
      time: '时间',
      reason: '原因',
      status: '状态',
      employee: '员工',
      reviewerNote: '审核备注',
      target: '目标',
      created: '创建时间',
      paid: '带薪',
      noDepartment: '不关联部门',
      noManager: '不关联负责人',
      allRoles: '全部角色',
      saveProject: '保存项目',
      saveHoliday: '保存节假日',
      submitRequest: '提交申请',
      updatedBy: '更新者',
      workingDays: '每周工作日',
      checkInTime: '签到时间',
      checkOutTime: '签退时间',
      earlyCheckInMinutes: '允许提前签到（分钟）',
      lunchStart: '午休开始',
      lunchEnd: '午休结束',
      lunchMinutes: '午休分钟数',
      morningHalfCoefficient: '上午半天系数',
      afternoonHalfCoefficient: '下午半天系数',
      otWorkingDay: '工作日加班系数',
      otDayOff: '休息日加班系数',
      otOfficialHoliday: '法定节假日加班系数',
      otCompensatoryHoliday: '调休节假日加班系数',
      closingDay: '月度考勤结算日',
      standardWorkingDays: '月标准工作天数',
      userId: '用户 ID',
      role: '角色',
      updateRole: '更新角色',
      userRoleHelp: '输入后端 userId 和新角色。',
    },
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('hr_language_mode');
    return (saved as Language) || 'vi'; // Default to Vietnamese
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('hr_language_mode', lang);
  };

  const value = useMemo(() => ({ language, setLanguage }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useTranslation() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }

  const { language, setLanguage } = context;

  const t = (key: string): string => {
    const keys = key.split('.');
    let current: any = translations[language];

    for (const k of keys) {
      if (current && typeof current === 'object' && k in current) {
        current = current[k];
      } else {
        // Fallback to English
        let fallback: any = translations['en'];
        for (const fk of keys) {
          if (fallback && typeof fallback === 'object' && fk in fallback) {
            fallback = fallback[fk];
          } else {
            return key; // return raw key if missing completely
          }
        }
        return typeof fallback === 'string' ? fallback : key;
      }
    }

    return typeof current === 'string' ? current : key;
  };

  return { t, language, setLanguage };
}
